/* ==========================================================================
  【作品データ一括管理ファイル】
  作品を追加・編集したい場合は、このファイルだけを更新してください。
  【コンテンツデータ】
  detail: { detail: "...", credit: "..." } を追加するとホバー時に表示されます
========================================================================== */
const WORKS = [
  // ---------------------------------------------------------------- 2026
  { title: "読谷あかねのリミナルスペースお散歩日記", tag: "その他", year:"2026", url: "https://youtu.be/B-nUHn-z9pk", img:"images/Liminal.png"},
  { title: "Vocation Chiba Vol.115", tag: "出演", year:"2026", url: "https://twipla.jp/events/727217", img:"images/Vocachiba.jpg"},
  { title: "#トモダチコレクションわくわく生活の服を着せて描く",  tag: "イラスト", year: "2026", url: "https://x.com/yomitanakane/status/2060283503816663067?s=20", img: "images/Tomocolle.png" },
  { title: "【テトライブ2026】重音テト合作【DJタイム】", tag: "その他", year:"2026", url: "https://www.nicovideo.jp/watch/sm46359764", 
	img:"images/TetoGassaku.jpg", detail:{detail:"テトライブ2026の上映動画", credit:"フロクロ,原口沙輔,読谷あかね,マサラダ,マキシウキョウ"}},
  { title: "たぶん誰でも楽しめるクイズ", tag: "その他", year:"2026", url: "https://yomitan-akane.booth.pm/items/8394486", img:"images/Quiz.png"},
  { title: "NIGHT HIKE -scramble-‘26", tag: "出演", year:"2026", url: "https://nighthike.net/news/yJvkULjM", img:"images/NIGHTHIKE26.jpg"},
  { title: "テトライブ2026", tag: "出演", year:"2026", url: "https://t.pia.jp/pia/event/event.do?eventBundleCd=b2563707", 
	img:"images/TetoLive2026.png"},
  { title: "2nd Album『ここはどこだ』", tag: "楽曲", year: "2026", img: "images/2ndAlbum.png", url:"https://yomitan-akane.booth.pm/items/8271541" },

  { title: "Kasane Interlink", tag: "楽曲", year: "2026", img: "images/Interlink.jpg", ytId:"NeBumfydQsI",
	detail:{detail:"『モアレ』収録"} },
  { title: "音と言葉 第二版", tag: "楽曲", year: "2026", img: "images/Kotoba2.jpg", ytId: "2kWrCtMgras" ,
	detail:{detail:"『已己巳己』『音と言葉マイクリレー 』収録"}},
  { title: "全部俺PART lll", tag: "楽曲", year: "2026", img: "images/ZenbuOre3.jpg", ytId:"dv0TEBkP9Tk" ,
	detail:{detail:"『異化効果』収録、他ブックレットイラスト等"}},

  { title: "2nd Album『ここはどこだ』リスニングテスト", tag: "楽曲", year: "2026", ytId: "DQn4SdnYTxo", img: "images/Listening.png" },
  { title: "DÉ DÉ MOUSE & KAJI『ZEUS』",  tag: "映像", year: "2026", ytId: "gYKcj3NEgiw", img: "images/ZEUS.png", 
		detail: { detail: "編集を担当", credit:"(公募イラストを全採用)" 
	} },
  { title: "同⇆同 / 重音テト", tag: "楽曲", year: "2026", ytId: "n87PL8pwMfw", img: "images/Dodo.png" },
  { title: "ビルド・トゥ・スクラップ / 重音テト", tag: "楽曲", year: "2026", ytId: "rXBqYHwNu0Y", img: "images/Build.png",
	detail:{credit:"映像：1時,コサンジ"} },
  {
    title: "ネイロノーツ feat. 式部めぐり", tag: "楽曲", year: "2026", ytId: "hXtsNr2S_Uo", img: "images/Neiro.png",
    detail: {
      detail: "プロモーション：HoYoverse",
      credit: "式部めぐり,大月,さぶろう,dedeen,桜木しの,れでぃば,tugutugu,荒木悟"
    }
  },
  { title: "CTC RECORDS HYPER POPUP EXTEND モニター映像", tag: "その他", year:"2026", url: "https://youtube.com/shorts/qhYLDgKTcoY?si=24XVTW2AKqFxTJU6", img:"images/CTC2Monitor.png",
	detail:{detail:"楽曲制作", credit:"Pensil./えいりな刃物/わたぴー"}},
  { title: "CTC RECORDS HYPER POPUP EXTEND", tag: "その他", year:"2026", url: "https://prtimes.jp/main/html/rd/p/000000014.000165142.html", img:"images/CTC2.jpg",
	detail:{detail:"グッズ・展示"}},
  { title: "VideoLAN", tag: "出演", year:"2026", url: "https://livepocket.jp/e/16x_u", img:"images/VideoLAN.jpg"},
  { title: "図々しい報酬系 / 重音テト", tag: "楽曲", year: "2026", ytId: "yNqhf9yi52g", img: "images/Zuzu.png" },
  { title: "0401 - The Best Days of 重音テト 2026", tag: "楽曲", year: "2026", url: "https://www.tkma.co.jp/new_release_detail/TKCA-75305.html", img: "images/BDT.jpg",
	detail:{detail:"『散り散り』収録"} },
  { title: "テトソニック2026", tag: "出演", year:"2026", url: "https://tetosonic.jp/", img:"images/TetoSonic.png"},
  { title: "CTC RECORDS各種グッズ", tag: "その他", year:"2026", url: "https://ctctyo.com/collections/ctcrecored-popup", img:"images/CTCGoods1.png"},
  { title: "CTC RECORDS HYPER POP UP STORE", tag: "その他", year:"2026", url: "https://prtimes.jp/main/html/rd/p/000000012.000165142.html", img:"images/CTC1.jpg",
	detail:{detail:"グッズ・展示"}},
  { title: "玉手箱「偏光」", tag: "楽曲", year: "2026", ytId: "-itXNDgEaYs", img: "images/Henko.jpg",
	detail:{detail:"『惑星プラネット』収録"} },
  { title: "テト 『弱者のマーチ』 アクスタキーホルダー",  tag: "イラスト", year: "2026", url: "https://eipu.booth.pm/items/7922942", 
	img: "images/Acrylic_Jakusha.jpg" },
  { title: "えいぷ『弱者のマーチ』",  tag: "映像", year: "2026", ytId: "IxSvgPhdc8c", img: "images/Jakusha.png"},
  { title: "リーパー / 重音テト", tag: "楽曲", year: "2026", ytId: "xpCwtcNNr2o", img: "images/REAPER.png" },
  { title: "Sou『Q.E.D.』",  tag: "映像", year: "2026", ytId: "7WGmWlaYMzI", img: "images/QED.png", detail: { detail: "編集・背景を担当", credit:"(多数のため省略)" } },

  // ---------------------------------------------------------------- 2025
  { title: "テト 『頭ン痛』 アクスタキーホルダー",  tag: "イラスト", year: "2025", url: "https://eipu.booth.pm/items/7720762", 
	img: "images/Acrylic_Atama.jpg" },
  { title: "ユリイカ2025年11月号　特集＝原口沙輔",  tag: "イラスト", year: "2025", url: "https://www.seidosha.co.jp/book/index.php?id=4078&status=published", img: "images/Eureka.png" },
  { title: "Break pxl", tag: "楽曲", year: "2025", ytId: "HQSKcifqK1Y", img: "images/Breakpxl.jpg",
	detail:{detail:"『ビルド・トゥ・スクラップ』収録"} },
  { title: "再終教育（syllabus）アフタートーク", tag: "出演", year:"2025", url: "https://hkcm.jimdofree.com/", img:"images/Syllabus.png"},
  { title: "マニュア / 重音テト",  tag: "楽曲", year: "2025", ytId: "BxsOTeSIe6E", img: "images/MANURE.png" },
  { title: "感状線『と～ぜんっ！』",  tag: "映像", year: "2025", ytId: "Za6ZyIhxnqE", img: "images/Tozen.png", detail: { credit: "編集：れでぃば(hifumi,inc.)" } },
  { title: "寂句 / 重音テト",    tag: "楽曲", year: "2025", ytId: "aF2Ws_2-meQ", img: "images/Jack.png" },
  { title: "テクノポップ・有機・シンセサイザーちゃん『エレクトリック・ミラージュ・感情』", tag: "映像", year: "2025", ytId: "03T0i2UpRw", img: "images/Electric.png",
	detail: { detail: "一部編集を担当", credit: "えいりな刃物,廣井結実,Cube,ミジンコ,荒木悟" } },
  { title: "消えないファイル / 重音テト",  tag: "楽曲", year: "2025", ytId: "Pea-FqG0IbY", img: "images/Kienai.png" },

  { title: "Yomitan-Reference", tag: "その他", year:"2025", url: "https://scrapbox.io/Yomitan-Reference/", img:"images/Reference.png" ,
	detail:{detail:"Cosenseページ"}},

  { title: "DigitalStars2025", tag: "出演", year:"2025", url: "https://digitalstars.club/hmds25/index.html", img:"images/DegiSta.png"},
  { title: "NIGHT HIKE Mid 2025 supported by ジンドゥー", tag: "出演", year:"2025", url: "https://nighthike.net/news/k_nszOdL", img:"images/NIGHTHIKE2025.jpg"},
  { title: "テトナイトごめんなさいセットリスト", tag: "その他", year:"2025", url: "https://www.nicovideo.jp/watch/sm45272051", img:"images/TetoNight.png"},
  { title: "重音テトナイト", tag: "出演", year:"2025", url: "https://x.com/vocabuki/status/1936771325672259805?s=20", img:"images/TetoNightF.jpg"},
  { title: "私立パラの丸高校『!! Bomb Cute Bomb !!』", tag: "映像", year: "2025", ytId: "BaAutzIHNV4", img: "images/Bomb.png",
		detail: { detail: "一部パートを担当", credit: "がちゃ,めだまやき,れたすじろう,Rumi(ルミリンゴ)" 
	} },
  { title: "ボドボカ", tag: "楽曲", year: "2025", ytId: "ANrKWMxK844", img: "images/BodoVoca.jpg",
	detail:{detail:"『10枚の絵でしりとりしながら曲作りたい』収録"} },
  { title: "佐藤ちなみに『押ス』",  tag: "映像", year: "2025", ytId: "FfsIKxn8SBM", img: "images/Osu.png" },
  { title: "ゴールドレディ / ナツメイツキ",   tag: "楽曲", year: "2025", ytId: "WOHp65f_B-U", img: "images/Gold.png" },
  { title: "ブレインウォッシャー / 重音テト", tag: "楽曲", year: "2025", ytId: "f34CglFrtDw", img: "images/Brain.png" },
  { title: "音と言葉", tag: "楽曲", year: "2025", ytId: "6YRF1jCQ9mY", img: "images/Kotoba1.jpg",
	detail:{detail:"『丌∘☋☡卅』収録"} },
  { title: "原口沙輔『タイムアウト代替ノイド』", tag: "映像", year: "2025", ytId: "4TEHMXrSlS0", img: "images/Timeout.png" },
  { title: "合わせ鏡のウワサ / 重音テト",     tag: "楽曲", year: "2025", ytId: "Rj-7bKAsNfk", img: "images/Awase.png" },
  { title: "サツキ『ファサード・クエスチョン』", tag: "映像", year: "2025", ytId: "njKdvdYQ-xE" , img: "images/FQ.png"},
  { title: "ミ瑞『エンド・オブ・フェイク！』", tag: "映像", year: "2025", ytId: "zLiRb7NzQBk", img: "images/EoF.png"},
  { title: "タケノコ少年『ユーエフオーにさらわれたい』", tag: "映像", year: "2025", ytId: "OEEZsnQCJFA", img: "images/UFO.png" },
  { title: "ひみつの小学生 近所 通学路 明るめ 色違い シークレット 水陸両用 誰", tag: "その他", year: "2025", ytId: "FdcXJ5fcRj4", img: "images/Himitsu.png", 
	detail: { detail: "稲葉曇『ひみつの小学生』REMIX" ,credit: "映像：こまり" } },
  { title: "虹捜索 / 重音テト",  tag: "楽曲", year: "2025", ytId: "6U0x5iWz5tI", img: "images/FunArc.png"},
  { title: "ボカコレプレイリスト「探ボ」",  tag: "その他", year: "2025", url: "https://vocaloid-collection.jp/2025-winter/playlist/creator/77500458/", img: "images/Tanbo.png" },
  { title: "逃ゲガチ (強制収録ver)",  tag: "楽曲", year: "2025", ytId: "6HaK8MsAFNw", img: "images/Nigegachi_Re.png", detail:{credit: "絵：えいりな刃物"} },
  { title: "はろー！にゅ～みゅーじっく！vol.24", tag: "出演", year:"2025", url: "https://vocaloid-collection.jp/2025-winter/playlist/creator/77500458/", img:"images/Hello.png"},
  { title: "春野『アレグロ』",  tag: "映像", year: "2025", ytId: "YX40ZDUIJT8",  img: "images/Allegro.png",
	detail: { detail: "編集を担当", credit: "my0nruri,torishima,廣井結実,Mikuron.,三束,もふじろ～。" } },

  // ---------------------------------------------------------------- 2024
  { title: "2代目閻魔 / 重音テト",  tag: "楽曲", year: "2024", ytId: "ATUpo33OvdA", img: "images/2Daime.png"},
  { title: "REEL",   tag: "映像", year: "2024", ytId: "wzUnRwoZ8yU", img: "images/REEL.png" },
  { title: "ボカタマ vol.3", tag: "出演", year:"2024", url: "https://twipla.jp/events/624698", img:"images/Vocatama.jpg"},
  { title: "ボーイズセイハロウ 超体操バージョンREMIX", tag: "その他", year: "2024", ytId: "G2Nt_1YXJlw" , img: "images/BSH.png", 
	detail: { detail: "Sohbana『ボーイズセイハロウ』Remix", credit: "えいりな刃物,わたぴー" } },
  { title: "?",   tag: "その他", year: "2024", url: "https://x.com/yomitanakane/status/1847243176257687821?s=20", img: "images/FEAT.png" ,
	detail:{detail:"非公式"}},
  { title: "【必見】朝の作り方 / 重音テト",   tag: "楽曲", year: "2024", ytId: "he3k2JuUDxo", img: "images/Asa.png" },
  { title: "狭っ苦しくてしゃあないわ / 重音テト", tag: "楽曲", year: "2024", ytId: "", img: "images/Sema.png" },
  { title: "とうかさ『満身創痍』", tag: "映像", year: "2024", ytId: "A2t0hvZTO4s", img: "images/Manshin.png" },
  { title: "潜リ在ル / 重音テト",   tag: "楽曲", year: "2024", ytId: "F1KTpY09Ls0", img: "images/Moguriaru.png" },
  { title: "真っっっっっ暗 / 葛駄夜音",  tag: "楽曲", year: "2024", ytId: "06HoljQ_WCI" , img: "images/Makkura.png"},
  { title: "SUZURIグッズ", tag: "その他", year:"2024", url: "https://suzuri.jp/yomitan", img:"images/SUZURI.jpg"},
  { title: "第2回パチミラ福岡", tag: "出演", year:"2024", url: "https://twipla.jp/events/620109", img:"images/Pachimira.png"},
  { title: "えいぷ『誹謗熱中症』",  tag: "イラスト", year: "2024", ytId: "k62uKjBF2yU", img: "images/Hibo.png", 
	 detail: {credit: "編集：藤原ハガネ" } },
  { title: "どうにかなっちゃいそう！(rework by CDs)』",  tag: "その他", year: "2024", ytId: "w02A1rBoJGk", img: "images/CDs2.png",
	detail: { detail: "0:00-0:56 映像/2:29-2:45 4:47- 音声" } },
  { title: "1st Albumリリース記念イラスト", tag: "イラスト", year: "2024", url: "https://x.com/yomitanakane/status/1821924404655485227?s=20", img: "images/1st_Chilly.png" },
  { title: "1st Album『どこに行くの』", tag: "楽曲", year: "2024", url: "https://linkco.re/EvEERUN4", img: "images/1stAlbum.png" },
  { title: "1st Album『どこに行くの』XFD", tag: "楽曲", year: "2024", ytId: "LfPTg-DSr2A", img: "images/XFD1.png" },
  { title: "AZKi『まいすとらてじー！』",  tag: "映像", year: "2024", ytId: "5rblP8pcRrI", img: "images/Strategy.png",
	detail: { detail: "編集を担当", credit:"Animation:れでぃば" } },
  { title: "可愛くてごめん (rework by CDs)』",  tag: "その他", year: "2024", ytId: "ZiJR8Tzx1Oo", img: "images/CDs1.png",
	detail: { detail: "0:42-1:09 2:44-3:09 映像(Animation:えいりな刃物)" } },
  { title: "『SHARK』", tag: "楽曲", year: "2024", ytId: "WRYbwMgsmj8",  img: "images/SHARK.png",
	 detail: { detail: "ゼンレスゾーンゼロ イメージソング", credit: "藍月なくる,えいりな刃物,荒木悟" } },
  { title: "擦過ス / 歌愛ユキ", tag: "楽曲", year: "2024", ytId: "TBIvvgmUg2E", img: "images/Sakkasu.png"  },
  { title: "ピノキオピー『ユーチューバー』",   tag: "映像", year: "2024", ytId: "lTUVw7wd5qY", img: "images/UTuber.png" ,
	 detail: { detail: "編集を担当", credit: "Animation:えいりな刃物" } },
  { title: "X頭身 / 重音テト", tag: "楽曲", year: "2024", ytId: "m5FMGvOPWd8", img: "images/XToshin.png" },
  { title: "キタニタツヤ『タナトフォビア』縦型広告", tag: "映像", year: "2024", ytId: "TC_D5ntB-O8", img: "images/Tanatofobia.png"},
  { title: "えいぷ『オーバーライド - 頭ン痛 Remix』",  tag: "イラスト", year: "2024", ytId: "3MOEy2ZTJto", img: "images/Over.png"},
  { title: "『散り散り』LINEスタンプ",  tag: "その他", year: "2024", url: "https://store.line.me/stickershop/product/26616370/ja", 
	img: "images/LINEChilly.png" },
  { title: "十何心月 / 和音マコ",  tag: "楽曲", year: "2024", ytId: "vHPSa4DNXOs", img: "images/Quibble.png" },
  { title: "しゃいと『もザいク』",  tag: "映像", year: "2024", ytId: "6q88TNAjLNA", img: "images/Mosaic.png" },
  { title: "DISH//ファンクラブ『皿組GOLD』紹介アニメーション", tag: "映像", year: "2024", url: "https://x.com/yomitanakane/status/1800104831966957773?s=20", img: "images/DISH.png",
	detail: { detail: "ライブ映像・音効" } },
  { title: "逃ゲガチ / 重音テト",   tag: "楽曲", year: "2024", ytId: "rWcm2w1e8l0" ,img:"images/Nigegachi.png" },
  { title: "なみぐる『言葉がサラダになっていく』", tag: "映像", year: "2024", ytId: "A8TnJL116r0", img:"images/Salad.png" ,
	detail: { detail: "編集を担当",credit: "illusts:my0nruri" } },
  { title: "えいぷ『頭ン痛』",   tag: "映像", year: "2024", ytId: "jneo_p9h6WI", img:"images/Atamanita.png" },
  { title: "遊遊『ハザードシンボル』",   tag: "映像", year: "2024", ytId: "UqTd2xkHWcI", img:"images/Hazard.png", 
	 detail: { credit: "映像補佐：えいりな刃物,のをか,れでぃば" } },
  { title: "テトクラごめんなさいセットリスト", tag: "その他", year:"2024", url: "https://www.nicovideo.jp/watch/sm43916102", img:"images/Tetokura.png"},
  { title: "テトクラ！", tag: "出演", year:"2024", url: "https://twipla.jp/events/567638", img:"images/TetoKuraF.jpg"},
  { title: "低画質の人 / 重音テト・ナースロボ_タイプT", tag: "楽曲", year: "2024", ytId: "YpVk-5YdiQI", img:"images/Teigashitsu.png" },
  { title: "NIKE AIR MAX／ずっと真夜中でいいのに。「にらちゃん集結」篇CM", tag: "映像", year: "2023", ytId: "pMcPu-grMmg", img:"images/NIKE.png",
	detail: { detail: "編集を担当", credit: "Director&Animator：えいりな刃物" } },
  { title: "harha『film』",  tag: "映像", year: "2024", ytId: "munNqjxUfNk", img:"images/film.png"},
  { title: "堀江晶太 feat.棗いつき『ストラゴヴィゴス』", tag: "映像", year: "2024", ytId: "ofG5dtdRB-A", img:"images/Struggle.png" },

  // ---------------------------------------------------------------- 2023

  { title: "ハルマ『うっせぇわ covered』",  tag: "映像", year: "2023", ytId: "kHo1oGgvb4Q", img:"images/Usseewa.png" ,
	 detail: { detail: "編集を担当", credit: "Director&Animator：えいりな刃物" } },
  { title: "GReeeeN - ひらり【ジャンプルーキー！コラボMV】",  tag: "その他", year: "2023", ytId: "9uUpcLP6rCo", img:"images/Greeeen.png" ,
	 detail: { detail: "MV内に『読谷あかね』が登場" } },
  { title: "Vtuberアプリ「IRIAM」WebCM",  tag: "映像", year: "2023", img:"images/IRIAM.png", url:"https://x.com/yomitanakane/status/1739145499956154464?s=20" ,
	detail:{detail:"構成・編集・台詞配置を担当", credit:"楽曲：フロクロ"}},
  { title: "春猿火『friction（Remix）feat. 梓川』", tag: "映像", year: "2023", ytId: "pd5--dCzfhw", img:"images/Friction.png" ,
	 detail: { detail: "編集を担当", credit: "Director&Animator：えいりな刃物" } },
  { title: "銀河鉄道999ミュージックビデオ制作プロジェクト", tag: "映像", year: "2023", ytId: "y3NuyLH4QBo", img: "images/999.png", 
	detail: { credit: "監修：水島精二(Hifumi,inc.)" } },
  { title: "Tonbi『赤椿のタンゴ』",  tag: "映像", year: "2023", ytId: "CSF86YtCs3g",img: "images/Tango.png" },
  { title: "大神ミオ『ナイトループ』",  tag: "映像", year: "2023", ytId: "sHA7CXeRKis", img: "images/NightLoop.png", 
	detail: { detail: "編集を担当", credit: "Director&Animator：えいりな刃物" } },
  { title: "神野メイ『愛の化粧』", tag: "映像", year: "2023", ytId: "WherGO6ppHM",img: "images/Kesho.png"},
  { title: "seiza『プラネテス』",  tag: "映像", year: "2023", ytId: "UPztJYCAnO4", img: "images/Planetes.png", detail: { detail: "脚本を担当",
	credit: "陽,吉永 藍,LINTALO,kouko (emma)" } },
  { title: "夏昏サカナ『エオ』",   tag: "映像", year: "2023", ytId: "WCnQNQk_dtI", img: "images/EO.png", detail: { credit: "編集：柯ノ月" } },
  { title: "來-Ray-『Knock Knock』", tag: "映像", year: "2023", ytId: "LdTubEzUrH4", img: "images/Knock.png" },
  { title: "じゃんぱ / 重音テト", tag: "楽曲", year: "2023", ytId: "e7Hv0hRFJzY", img: "images/Jumpup.png"},
  { title: "あみだくじ / 重音テト", tag: "楽曲", year: "2023", ytId: "yFGwKkONYE4", img: "images/Amida.png"},
  { title: "木弟子『あゝ怠惰』", tag: "映像", year: "2023", ytId: "N83YUgomNaA", img: "images/Taida.png" },
  { title: "やまぐち『調律と呼吸器』",  tag: "映像", year: "2023", ytId: "UFq41qaMLaM", detail: { credit: "編集：雪乃" },img: "images/Choritsu.png" },
  { title: "ABテスト / 重音テト",  tag: "楽曲", year: "2023", img: "images/AB.png",ytId: "ZTT_I9R0qac" },
  { title: "開票速報 / 重音テト",  tag: "楽曲", year: "2023", img: "images/Kaihyo.png", ytId: "RhKKtWOUU4U" },
  { title: "ピーチパイボーイズ『ラビンソン』", tag: "映像", year: "2023", img: "images/Lovin.png", ytId: "dTSLQsRilH4"},
  { title: "散り散り / 重音テト",  tag: "楽曲", year: "2023", img: "images/Chilly.png", ytId: "Xn-JobZlsQo" },
  { title: "あたし『ちゅーして』",   tag: "映像", year: "2023", img: "images/Chu.png", ytId: "LzHRf3gmMp0" },
  { title: "短編", tag: "映像", year: "2023", img: "images/Doughnut.png", url: "https://x.com/yomitanakane/status/1631580169898184704?s=20" },
  { title: "短編", tag: "映像", year: "2023", img: "images/Mensetsu.png", url: "https://x.com/yomitanakane/status/1625781971375869953?s=20" },
  { title: "Sohbana『はなれあうゼロ』", tag: "映像", year: "2023", img: "images/Zero.png", ytId: "YY9Xk3J9ioU" },
  { title: "saireki『ポリへドロン』",  tag: "映像", year: "2023", img: "images/Polyh.png", ytId: "W7hQILue98U",
    detail: {
      credit: "Illustration - pikuson"
    }
  },
  { title: "神野メイ『ナイトラボ』",           tag: "映像", year: "2023", img: "images/Nightlabo.png", ytId: "TO5vNy3GplI" },
  { title: "來-Ray-『Domino Mask』",           tag: "映像", year: "2023", img: "images/DominoMask.png", ytId: "jDfTsXAO2DU" },

  // ---------------------------------------------------------------- 2022
  { title: "短編",  tag: "映像", year: "2022", img: "images/Vegetable.png", url: "https://x.com/yomitanakane/status/1589203261999185920?s=20" },
  { title: "短編",  tag: "映像", year: "2022", img: "images/MagicGirl.png", url: "https://x.com/yomitanakane/status/1562726482882936833?s=20" },
  { title: "au『その先に、「好き」な世界がきっとある。』CM", tag: "映像", year: "2022", img: "images/au.png", ytId: "Xgtk9BJr1OY", detail: { detail: "一部彩色のみ担当" } },
  { title: "泉 / Fontaine",  tag: "映像", year: "2022", img: "images/Fontaine.png", ytId: "bbGgNYhufYw" },
　{ title: "読谷あかね",  tag: "その他", year: "2021", img: "images/Comic.png", url: "https://manga.nicovideo.jp/comic/55592" },
];



